
name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup packages
      run: npm ci

    - name: Build
      run: npx webpack --mode=production

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build
